---    
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: CarolClusterBinding
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:prometheus
roleRef:
  kind: ClusterRole
  name: carol-role
  apiGroup: rbac.authorization.k8s.io
