apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    app: paymentservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - image: vkryukov/paymentservice:v0.0.2
        name: payment
        resources: {}
      dnsPolicy: ClusterFirst
